"""empty message

Revision ID: 13c17ad36a18
Revises: 8401b47ff1d6
Create Date: 2018-09-09 15:34:54.990257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13c17ad36a18'
down_revision = '8401b47ff1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImageMP', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('ImageMP', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.drop_column('ImageMP', 'modified')
    op.drop_column('ImageMP', 'created')
    op.add_column('TextMP', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('TextMP', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.drop_column('TextMP', 'modified')
    op.drop_column('TextMP', 'created')
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.drop_column('users', 'modified')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'date_modified')
    op.drop_column('users', 'date_created')
    op.add_column('TextMP', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('TextMP', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('TextMP', 'date_modified')
    op.drop_column('TextMP', 'date_created')
    op.add_column('ImageMP', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ImageMP', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ImageMP', 'date_modified')
    op.drop_column('ImageMP', 'date_created')
    # ### end Alembic commands ###
